[project]
name = "html-builder"
version = "0.1.0"
description = "Build HTML files piece-by-piece using Python."
readme = "readme.md"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.2.3",
]
